export type Brand = any;
export type BusinessSettings = any;
export type CartItem = any;
export type CashRegister = any;
export type Category = any;
export type Currency = any;
export type Customer = any;
export type CustomerGroup = any;
export type ErpModuleId = any;
export type Expense = any;
export type FinancialAccount = any;
export type Location = any;
export type Product = { id: string; currentStock: number; stock?: number; locationStocks?: Record<string, number>; lots?: any[]; costPrice?: number; sellingPrice?: number; [key: string]: any; };
export type ProductLot = any;
export type PurchaseRequisition = any;
export type PurchaseRequisitionItem = any;
export type RackLocation = any;
export type RegisterInput = any;
export type RolePermissions = any;
export type RolePermissionsMap = any;
export type SettingsSubTab = any;
export type UserMenuSubTab = any;
export type StockAdjustment = any;
export type StockTransfer = any;
export type Supplier = any;
export type SuspendedSale = any;
export type TaxGroup = any;
export type TaxRate = any;
export type Transaction = any;
export type TransactionItem = any;
export type TransactionStatus = any;
export type TransactionType = any;
export type PaymentEntry = any;
export type PaymentMethod = any;
export type PaymentMethodItem = any;
export type PaymentStatus = any;
export type Unit = any;
export type User = any;
export type UserRole = any;
export interface CustomRoleDefinition {
  id: string;
  roleKey: string;
  title: string;
  tier: string;
  badgeColor: string;
  description: string;
  allowedModules: ErpModuleId[];
  isCustom?: boolean;
}
export interface UserSession {
  id: string;
  userId: string;
  userName: string;
  userEmail: string;
  userRole: string;
  ipAddress: string;
  userAgent: string;
  deviceType: 'desktop' | 'mobile' | 'tablet' | 'pos_terminal';
  browser: string;
  os: string;
  locationId?: string;
  locationName?: string;
  loginTime: string;
  lastActiveTime: string;
  token: string;
  status: 'active' | 'idle' | 'expired' | 'revoked';
  isCurrentSession?: boolean;
}
export type SalesCommissionAgent = any;
export type SalesCommissionAgentType = any;
export type Warranty = any;
export type WarrantyDurationType = any;
export type QueuedTransaction = any;
export type SyncLogEntry = any;
export type OfflineSyncStats = any;
export type NotificationTemplate = any;
export type NotificationType = any;
export type NotificationChannel = any;
export type NotificationDeliveryLog = any;
export interface VariationTemplate {
  id: string;
  name: string;
  values: string[];
}
export type ProductAttribute = VariationTemplate;
export type ProductVariation = any;
export type ComboItem = any;
export type StockAdjustmentItem = any;
export type InvoiceLayoutType = any;
export type InvoiceLayoutConfig = any;
export type NotificationCategory = any;
export type StockAccountingMethod = any;
export type SalesItemAdditionMethod = any;
export type AmountRoundingMethod = any;
export type ProductExpiryAction = any;
export type PaymentTermsPreset = any;
export type TaxCalculationMode = any;
export type TaxSystemType = any;
export type CommissionCalculationType = any;
export type InvoiceScheme = any;
